export const HOTSECTION = [
  {
    id: 1,
    name: 'KU CASINO',
    bg: '/sideRight/livehotBG.png',
    icon: '/KU_logo.svg',
    img: '/sideRight/hotlive.png',
    width: 300,
    height: 300,
  },
  {
    id: 2,
    name: 'KU XỔ SỐ',
    bg: '/sideRight/lotoHotBG.png',
    icon: '/KU_logo.svg',
    img: '/sideRight/hotLoto.png',
  },
  {
    id: 3,
    name: 'KU THỂ THAO',
    bg: '/sideRight/sportHotBG.png',
    icon: '/KU_logo.svg',
    img: '/sideRight/hotOT.png',
  },
  {
    id: 4,
    name: '3D GAMES',
    bg: '/sideRight/slotHotBG.png',
    icon: '/KU_logo.svg',
    img: '/sideRight/hotOT2.png',
  },
  {
    id: 5,
    name: 'COOL - IN LIVE',
    bg: '/sideRight/hotBG.png',
    icon: '/sideRight/live.svg',
    img: '/sideRight/hotOT_CI.png',
  },
];

export const LIVESECTION = [
  {
    id: 1,
    name: 'KU',
    icon: '/KU_logo.svg',
    img: '/mobileIcon/img_liveOT_1.png',
    isHot: true,
    isSpan: true,
    isBg: true,
  },
  {
    id: 2,
    name: 'DG',
    icon: '/icons/logo_DG.png',
    img: '/mobileIcon/img_liveOT_2.png',
    isSmall: true,
  },
  {
    id: 3,
    name: 'AES',
    icon: '/icons/logo_AES.png',
    img: '/mobileIcon/img_liveOT_3.png',
    isSmall: true,
  },
  {
    id: 4,
    name: 'EVO',
    icon: '/icons/logo_EVO.png',
    img: '/mobileIcon/img_liveOT_4.png',
    isSmall: true,
  },
  {
    id: 5,
    name: 'WM',
    icon: '/icons/logo_WM.png',
    img: '/mobileIcon/img_liveOT_5.png',
    isSmall: true,
  },
  {
    id: 6,
    name: 'AG',
    icon: '/icons/logo_AG.png',
    img: '/mobileIcon/img_liveOT_6.png',
    isSmall: true,
  },
  {
    id: 7,
    name: 'SA',
    icon: '/icons/logo_SA.png',
    img: '/mobileIcon/img_liveOT_7.png',
    isSmall: true,
  },
  {
    id: 8,
    name: 'GPI',
    icon: '/icons/logo_GPI.png',
    img: '/mobileIcon/img_liveOT_8.png',
    isSmall: true,
  },
  {
    id: 9,
    name: 'DB',
    icon: '/icons/logo_DB.png',
    img: '/mobileIcon/img_liveOT_9.png',
    isSmall: true,
  },
];

export const XOSOSECTION = [
  {
    id: 1,
    name: 'KU',
    icon: '/KU_logo.svg',
    img: '/sideRight/img_xoso_1.png',
    isHot: true,
  },
  {
    id: 2,
    name: 'BBIN',
    icon: '/icons/logo_BBIN.png',
    img: '/sideRight/img_xoso_2.png',
  },
];
export const SPORTSECTION = [
  {
    id: 1,
    name: 'KU',
    icon: '/KU_logo.svg',
    img: '/mobileIcon/img_sportOT_1.png',
    isHot: true,
    isSpan: true,
  },
  {
    id: 2,
    name: 'JZ',
    icon: '/icons/logo_JZ.png',
    img: '/mobileIcon/img_sportOT_2.png',
    isSmall: true,
  },
  {
    id: 3,
    name: 'SABA',
    icon: '/icons/logo_OneBook.png',
    img: '/mobileIcon/img_sportOT_3.png',
    isSmall: true,
  },
  {
    id: 4,
    name: 'CMD',
    icon: '/icons/logo_CMD.png',
    img: '/mobileIcon/img_sportOT_4.png',
    isSmall: true,
  },
  {
    id: 5,
    name: 'AI',
    icon: '/icons/logo_AI.png',
    img: '/mobileIcon/img_sportOT_5.png',
    isSmall: true,
  },
  {
    id: 6,
    name: 'AG',
    icon: '/icons/logo_AG.png',
    img: '/mobileIcon/img_sportOT_6.png',
    isSmall: true,
  },
  {
    id: 7,
    name: 'PANDA',
    icon: '/icons/logo_OBsport.png',
    img: '/mobileIcon/img_sportOT_7.png',
    isSmall: true,
  },
];

export const GAMESECTION = [
  {
    id: 1,
    name: '3D',
    icon: '/KU_logo.svg',
    img: '/mobileIcon/img_slotOT_1.png',
    isHot: true,
    isSmall: true,
  },
  {
    id: 2,
    name: 'PG',
    icon: '/icons/logo_PG.png',
    img: '/mobileIcon/img_slotOT_2.png',
    isSmall: true,
  },
  {
    id: 3,
    name: 'FC',
    icon: '/icons/logo_FC.png',
    img: '/mobileIcon/img_slotOT_3.png',
    isSmall: true,
    isNew: true,
  },
  {
    id: 4,
    name: 'BNG',
    icon: '/icons/logo_BNG.png',
    img: '/mobileIcon/img_slotOT_4.png',
    isSmall: true,
  },
  {
    id: 5,
    name: 'CQ9',
    icon: '/icons/logo_CQ9.png',
    img: '/mobileIcon/img_slotOT_5.png',
    isSmall: true,
  },
  {
    id: 6,
    name: 'DS',
    icon: '/icons/logo_DS.png',
    img: '/mobileIcon/img_slotOT_6.png',
    isSmall: true,
  },
  {
    id: 7,
    name: 'PLS',
    icon: '/icons/logo_PLS.png',
    img: '/mobileIcon/img_slotOT_7.png',
    isSmall: true,
  },
  {
    id: 8,
    name: 'KA',
    icon: '/icons/logo_KA.png',
    img: '/mobileIcon/img_slotOT_8.png',
    isSmall: true,
  },
  {
    id: 9,
    name: 'FTG',
    icon: '/icons/logo_FTG.png',
    img: '/mobileIcon/img_slotOT_9.png',
    isSmall: true,
  },
  {
    id: 10,
    name: 'RK5',
    icon: '/icons/logo_RK5.png',
    img: '/mobileIcon/img_slotOT_10.png',
    isSmall: true,
  },
];

export const FIGHTSECTION = [
  {
    id: 1,
    name: '3D',
    icon: '/KU_logo.svg',
    img: '/mobileIcon/img_chessOT_1.png',
    isHot: true,
    isBig: true,
  },
  {
    id: 2,
    name: 'V8',
    icon: '/icons/logo_V8.png',
    img: '/mobileIcon/img_chessOT_2.png',
    isBig: true,
  },
];

export const FISHSECTION = [
  {
    id: 1,
    name: '3D',
    icon: '/KU_logo.svg',
    img: '/mobileIcon/img_fishOT_1.png',
    isHot: true,
    isSmall: true,
  },
  {
    id: 2,
    name: 'DS',
    icon: '/icons/logo_DS.png',
    img: '/mobileIcon/img_fishOT_2.png',
    isSmall: true,
  },
  {
    id: 3,
    name: 'KS',
    icon: '/icons/logo_KS.png',
    img: '/mobileIcon/img_fishOT_3.png',
    isSmall: true,
  },
  {
    id: 4,
    name: 'CQ9',
    icon: '/icons/logo_CQ9.png',
    img: '/mobileIcon/img_fishOT_4.png',
    isSmall: true,
  },
  {
    id: 5,
    name: 'AG',
    icon: '/icons/logo_AG.png',
    img: '/mobileIcon/img_fishOT_5.png',
    isSmall: true,
  },
  {
    id: 6,
    name: 'KA',
    icon: '/icons/logo_KA.png',
    img: '/mobileIcon/img_fishOT_6.png',
    isSmall: true,
  },
  {
    id: 7,
    name: 'V8',
    icon: '/icons/logo_V8.png',
    img: '/mobileIcon/img_fishOT_7.png',
    isSmall: true,
  },
  {
    id: 8,
    name: 'DB',
    icon: '/icons/logo_DB.png',
    img: '/mobileIcon/img_fishOT_8.png',
    isSmall: true,
  },
];

export const ESPORTSECTION = [
  {
    id: 1,
    name: 'IM',
    icon: '/icons/logo_IM.png',
    img: '/mobileIcon/img_esportsOT_1.png',
    isBig: true,
  },
  {
    id: 2,
    name: 'SHABA',
    icon: '/icons/logo_OneBook.png',
    img: '/mobileIcon/img_esportsOT_2.png',
    isBig: true,
  },
];
